namespace Bifrost.ConstEnum
{
	public enum DefAction
	{
		Invalid = 0,
		MAP_COMPLETE = 1,
		SESSION_DECISION = 2,
		ACTIVATE_SPAWNPOINT = 3,
		PLAY_SOUND = 4,
		CHANGE_MUTABLE_STAT = 5,
		CHANGE_MUTABLE_STAT_RANDOM = 6,
		DECREASE_ITEM_COUNT = 7,
		ADD_ABNORMAL = 8,
		TELEPORT = 9,
		HANDLE_LEVELOBJECT = 10,
		INSTANT_KILL = 11,
		SPAWN_FIELD_SKILL = 12,
		PLAY_ANIMATION = 13,
		PLAY_CUTSCENE = 14,
		SPAWN_FIELD_SKILL_MAPMARKER = 15,
		WAIT = 16,
		ARCHIVE_LOOTING_OBJECT = 17,
		RESPAWN_ARCHIVED_OBJECT = 18,
		CHARGE_ITEM = 19,
		TELEPORT_TO_SPAWNPOINT = 20,
		SPAWN_FIELD_SKILL_RANDOM = 21,
		RANDOM_TELEPORT = 22,
		ENABLE_AI = 23,
		CHANGE_TRAM_PARTS = 24,
		REMOVE_FIELD_SKILL_NEARBY = 25,
		REBUILD_NAVMESH = 26,
		SETINVINCIBLE = 27
	}
}
